import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/context/cartContextProvider";
import { UserContextProvider } from "@/context/userContextProvider";
import { LoginContextProvider } from "@/context/loginContextProvider";
import SessionWrapper from "@/components/SessionWrapper";
import { WishlistProvider } from "@/context/wishlistContextProvider";
import { SidebarProvider } from "@/context/sidebarContext";
import Sidebar from "@/components/universal/sidebar";

export const metadata: Metadata = {
  title: "BANDAGE STORE",
  description: "Generated by Abdul Basit Khalsai",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      > 
        <SessionWrapper>
        <SidebarProvider>
        <LoginContextProvider>
        <UserContextProvider>
        <SidebarProvider>
        <WishlistProvider>
        <CartProvider>
        <Sidebar userId="USER0001"/>
        {children}
        </CartProvider>
        </WishlistProvider>
        </SidebarProvider>
        </UserContextProvider>
        </LoginContextProvider>
        </SidebarProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
